# Generated by Django 4.2.9 on 2025-12-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField()),
                ("diagnosis", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="doctors.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "Appointments",
                "indexes": [
                    models.Index(
                        fields=["patient"], name="Appointment_patient_433b03_idx"
                    ),
                    models.Index(
                        fields=["doctor"], name="Appointment_doctor__2f2b31_idx"
                    ),
                ],
            },
        ),
    ]
