# Generated by Django 4.2.9 on 2025-12-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="visit_date",
            field=models.DateTimeField(),
        ),
    ]
