# Generated by Django 4.2.9 on 2025-12-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("middle_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(max_length=50)),
                ("dob", models.DateField()),
                ("ethnicity", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "preferred_language",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gender", models.CharField(max_length=20)),
                ("biological_sex", models.CharField(max_length=20)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("first_visit_date", models.DateField()),
                ("last_visit_date", models.DateField()),
                (
                    "insurance_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "insurance_provider",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("blood_type", models.CharField(blank=True, max_length=10, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("dnr_status", models.BooleanField(default=False)),
                ("organ_donor_status", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "Patient",
            },
        ),
        migrations.CreateModel(
            name="PatientPersonalInformation",
            fields=[
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="patients.patient",
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=100, null=True)),
                ("nat_id", models.CharField(blank=True, max_length=50, null=True)),
                ("passport_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "drivers_license_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "PatientPersonalInformation",
            },
        ),
        migrations.CreateModel(
            name="PatientEmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_type", models.CharField(max_length=50)),
                ("contact_information", models.CharField(max_length=255)),
                ("relationship", models.CharField(max_length=50)),
                ("last_updated", models.DateField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "PatientEmergencyContact",
            },
        ),
        migrations.CreateModel(
            name="PatientCoreMedicalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("information_type", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="core_med_info",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "db_table": "PatientCoreMedicalInformation",
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["last_name"], name="Patient_last_na_f8bd0d_idx"),
        ),
    ]
