# Generated by Django 4.2.9 on 2025-12-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCoreMedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Core Medical Information',
                'verbose_name_plural': 'Core Medical Information',
                'db_table': 'Type_CoreMedInfo',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='patientcoremedicalinformation',
            name='information_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_med__info_type', to='patients.patient'),
        ),
    ]
