# Generated by Django 4.2.9 on 2025-12-25 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_typecoremedinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcoremedicalinformation',
            name='information_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_med_info_type', to='patients.patient'),
        ),
    ]
