# Generated by Django 4.2.9 on 2025-12-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientcoremedicalinformation_information_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcoremedicalinformation',
            name='information_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.typecoremedinfo'),
        ),
    ]
