# Generated by Django 4.2.9 on 2025-12-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                ("producer", models.CharField(blank=True, max_length=100, null=True)),
                ("medicine_unit", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Medicine",
                "verbose_name_plural": "Medicine",
                "db_table": "Medicine",
                "ordering": ["medicine_name"],
            },
        ),
        migrations.CreateModel(
            name="TypeCoreMedInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Core Medical Information",
                "verbose_name_plural": "Core Medical Information",
                "db_table": "Type_CoreMedInfo",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TypeMedicineAdministration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Medicine Administration Method",
                "verbose_name_plural": "Medicine Administration Methods",
                "db_table": "Type_MedicineAdministration",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TypeMedicineFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Medicine Function",
                "verbose_name_plural": "Medicine Functions",
                "db_table": "Type_MedicineFunction",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MedicineStockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_remove", models.BooleanField()),
                ("amount", models.IntegerField()),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_history",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.medicine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicine Stock History",
                "verbose_name_plural": "Medicine Stock History",
                "db_table": "MedicineStockHistory",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="medicine",
            name="medicine_administration_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pharmacy.typemedicineadministration",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="medicine_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pharmacy.typemedicinefunction",
            ),
        ),
    ]
