# Generated by Django 4.2.9 on 2025-12-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeCoreMedInfo',
        ),
    ]
