# Generated by Django 4.2.9 on 2025-12-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_alter_appointment_visit_date"),
        ("pharmacy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicinestockhistory",
            name="appointment_id",
        ),
        migrations.RemoveField(
            model_name="prescriptionhistory",
            name="appointment_id",
        ),
        migrations.AddField(
            model_name="medicinestockhistory",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_history",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionhistory",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to="appointments.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="medicine_administration_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pharmacy.typemedicineadministration",
            ),
        ),
        migrations.AlterField(
            model_name="medicine",
            name="medicine_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="pharmacy.typemedicinefunction",
            ),
        ),
    ]
