# Generated by Django 4.2.9 on 2025-12-18 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                ("producer", models.CharField(blank=True, max_length=100, null=True)),
                ("medicine_unit", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "Medicine",
            },
        ),
        migrations.CreateModel(
            name="TypeCoreMedInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Type_CoreMedInfo",
            },
        ),
        migrations.CreateModel(
            name="TypeMedicineAdministration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Type_MedicineAdministration",
            },
        ),
        migrations.CreateModel(
            name="TypeMedicineFunction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "Type_MedicineFunction",
            },
        ),
        migrations.CreateModel(
            name="PrescriptionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_id", models.IntegerField()),
                ("prescription_date", models.DateField(blank=True, null=True)),
                ("amount", models.IntegerField()),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacy.medicine",
                    ),
                ),
            ],
            options={
                "db_table": "PrescriptionHistory",
            },
        ),
        migrations.CreateModel(
            name="MedicineStockHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_remove", models.BooleanField()),
                ("amount", models.IntegerField()),
                ("appointment_id", models.IntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pharmacy.medicine",
                    ),
                ),
            ],
            options={
                "db_table": "MedicineStockHistory",
            },
        ),
        migrations.AddField(
            model_name="medicine",
            name="medicine_administration_method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pharmacy.typemedicineadministration",
            ),
        ),
        migrations.AddField(
            model_name="medicine",
            name="medicine_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="pharmacy.typemedicinefunction",
            ),
        ),
    ]
